const numbers = {
  0: [
    { label: "a", active: true },
    { label: "b", active: true },
    { label: "c", active: true },
    { label: "d", active: true },
    { label: "e", active: true },
    { label: "f", active: true },
    { label: "g", active: false },
  ],
  1: [
    { label: "a", active: false },
    { label: "b", active: true },
    { label: "c", active: true },
    { label: "d", active: false },
    { label: "e", active: false },
    { label: "f", active: false },
    { label: "g", active: false },
  ],
  2: [
    { label: "a", active: true },
    { label: "b", active: true },
    { label: "c", active: false },
    { label: "d", active: true },
    { label: "e", active: true },
    { label: "f", active: false },
    { label: "g", active: true },
  ],
  3: [
    { label: "a", active: true },
    { label: "b", active: true },
    { label: "c", active: true },
    { label: "d", active: true },
    { label: "e", active: false },
    { label: "f", active: false },
    { label: "g", active: true },
  ],
  4: [
    { label: "a", active: false },
    { label: "b", active: true },
    { label: "c", active: true },
    { label: "d", active: false },
    { label: "e", active: false },
    { label: "f", active: true },
    { label: "g", active: true },
  ],
  5: [
    { label: "a", active: true },
    { label: "b", active: false },
    { label: "c", active: true },
    { label: "d", active: true },
    { label: "e", active: false },
    { label: "f", active: true },
    { label: "g", active: true },
  ],
  6: [
    { label: "a", active: true },
    { label: "b", active: false },
    { label: "c", active: true },
    { label: "d", active: true },
    { label: "e", active: true },
    { label: "f", active: true },
    { label: "g", active: true },
  ],
  7: [
    { label: "a", active: true },
    { label: "b", active: true },
    { label: "c", active: true },
    { label: "d", active: false },
    { label: "e", active: false },
    { label: "f", active: false },
    { label: "g", active: false },
  ],
  8: [
    { label: "a", active: true },
    { label: "b", active: true },
    { label: "c", active: true },
    { label: "d", active: true },
    { label: "e", active: true },
    { label: "f", active: true },
    { label: "g", active: true },
  ],
  9: [
    { label: "a", active: true },
    { label: "b", active: true },
    { label: "c", active: true },
    { label: "d", active: true },
    { label: "e", active: false },
    { label: "f", active: true },
    { label: "g", active: true },
  ],
};

export default function getSegments(value) {
  return numbers[value];
}
